pytesseract_django_sample/urls.py
from django.contrib import admin
from django.urls import path

from ocr_sample.views import ocr_index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', ocr_index, name='ocr_index')
]

ocr_sample/models.py
from django.db import models

# Create your models here.

ocr_sample/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2022 Junction Applications
# Author: Aaron MacGillivary
# Project: pytesseract_django_sample

from django import forms


class UploadFileForm(forms.Form):
    """
    Simplest of forms to provide file upload
    """
    file_upload = forms.FileField()

ocr_sample/views.py
import tempfile
from PIL import Image
from django.shortcuts import render
from pytesseract import pytesseract
from ocr_sample.forms import UploadFileForm


def ocr_index(request):
    context = dict()

    # Windows users need to add something like:
    # pytesseract.pytesseract.tesseract.cmd = "C:/Program Files/Tesseract-OCR/tesseract.exe"

    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():

            image = Image.open(request.FILES['file_upload'])
            image_text = pytesseract.image_to_string(image)

            # If you were handling larger files, perhaps something like this would be better
            # with tempfile.TemporaryFile() as temp_file:
            #     for chunk in request.FILES['file_upload'].chunks():
            #         temp_file.write(chunk)
            #     image = Image.open(temp_file)
            #     image_text = pytesseract.image_to_string(image)

            context.update({'image_text': image_text, })
            # reset the form: typically we'd redirect elsewhere to prevent multiple
            # submissions of data, but there is no database interaction here - only
            # sending the text back
            form = UploadFileForm()
    else:
        form = UploadFileForm()

    context.update({'form': form, })

    return render(request, "ocr_sample/ocr_index.html", context)

ocr_sample/templates/ocr_sample/ocr_index.html
{% extends "base.html" %}
{% block main_content %}
  <div class="bg-white">
    <div class="max-w-7xl mx-auto text-center py-12 px-4 sm:px-6 lg:py-16 lg:px-8">
      <h2 class="text-3xl font-extrabold tracking-tight text-gray-900 sm:text-4xl">
        <span class="block">Pytesseract/Django</span>
        <span class="block">Sample Application</span>
      </h2>

      <div class="sm:pt-5 max-w-lg mx-auto">
        <label for="cover-photo" class="block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2"> Extract Text from Image File </label>
        <form id="id_file_upload_form" action="{% url "ocr_index" %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div id="id-drop-area" class="flex justify-center px-6 pt-5 pb-6 border-2 border-gray-300 border-dashed rounded-md">
            <div class="space-y-1 text-center">
              <svg class="mx-auto h-12 w-12 text-gray-400" stroke="currentColor" fill="none" viewBox="0 0 48 48" aria-hidden="true">
                <path
                    d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02"
                    stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
              <div class="flex text-sm text-gray-600">
                <label for="id_file_upload"
                       class="relative cursor-pointer bg-white rounded-md font-medium text-indigo-600
                       hover:text-indigo-500 focus-within:outline-none focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-indigo-500">
                  <span>Upload a file</span>
                  <input name="file_upload" type="file" class="sr-only" required="" id="id_file_upload">
                </label>
                <p class="pl-1">or drag and drop</p>
              </div>
              <p class="text-xs text-gray-500">PNG, JPG, GIF up to 10MB</p>
            </div>
          </div>
          <div class="mt-3 rounded-md sm:mt-0 sm:flex-shrink-0">
            <button type="submit"
                    class="w-full bg-sky-800 border border-transparent rounded-md py-2 px-4 flex items-center justify-center text-base font-medium text-white
                    hover:bg-sky-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-sky-500">
              Run OCR
            </button>
          </div>
        </form>
      </div>

      {% if image_text  %}
      <div class="mt-4 sm:pt-5 max-w-3xl mx-auto border border-gray-300 p-4 bg-gray-50 text-gray-800">
        {{ image_text }}
      </div>
      {% endif %}
    </div>
  </div>

{% endblock %}

{% block scripts %}
<script>
    ;[document.getElementById('id-drop-area')].forEach(
        da => {

            ;['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {
                da.addEventListener(eventName, function(e){
                    e.preventDefault()
                    e.stopPropagation()
                }, false)
            })

            ;['dragenter', 'dragover'].forEach(eventName => {
                da.addEventListener(eventName, function(e){
                    da.classList.remove('border-gray-600')
                    da.classList.add('border-sky-800', 'shadow-xl', 'shadow-sky-400', 'bg-sky-100')
                }, false)
            })

            ;['dragleave'].forEach(eventName => {
                da.addEventListener(eventName, function(e){
                    da.classList.remove('border-sky-800', 'shadow-xl', 'shadow-sky-400', 'bg-sky-100')
                    da.classList.add('border-gray-600')
                }, false)
            })

            ;['drop'].forEach(eventName => {
                da.addEventListener(eventName, function(e){
                    da.classList.remove('border-sky-800', 'shadow-xl', 'shadow-sky-400', 'bg-sky-100')
                    da.classList.add('border-gray-600')
                    da.querySelector('#id_file_upload').files = e.dataTransfer.files

                }, false)
            })

        }
    )
</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>OCR Sample</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <!-- page content -->
    {% block main_content %}{% endblock %}

  <footer class="container max-w-3xl mx-auto" aria-labelledby="footer-heading">

    <div class="border-t border-b border-gray-700 py-8 px-4 lg:flex lg:items-center lg:justify-between xl:mt-0">
      <div>
        <h3 class="text-sm font-semibold text-gray-800 tracking-wider uppercase">Sample Application</h3>
        <p class="mt-2 text-base text-gray-600">Demonstrates one way to use Pytesseract with a Django Application.</p>
      </div>
      <svg class="h-12" version="1.1" viewBox="0 0 142.4411 39.51762" xmlns="http://www.w3.org/2000/svg" >
        <g transform="translate(-32.137 -85.589)">
        <text x="114.76616" y="122.31431" fill="#8baabf" font-family="Sans" font-size="8.4631px" letter-spacing="0px" stroke-width=".21158px" word-spacing="0px" style="line-height:125%" xml:space="preserve"><tspan x="114.76616" y="122.31431" fill="#8baabf" stroke-width=".21158px">APPLICATIONS</tspan></text>
        <text x="77.787567" y="110.91517" fill="#191d1f" font-family="Cantarell" font-size="26.322px" font-weight="bold" letter-spacing="0px" stroke-width=".65806px" word-spacing="0px" style="font-feature-settings:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-variant-numeric:normal;line-height:125%" xml:space="preserve"><tspan x="77.787567" y="110.91517" fill="#191d1f" font-family="Cantarell" font-size="26.322px" font-weight="bold" stroke-width=".65806px" style="font-feature-settings:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-variant-numeric:normal">junction</tspan></text>
        <g transform="translate(13.454 -280.79)">
        <path d="m51.476 386.13-5.9303-3.2606v1.7079h-0.58651c-2.5741 0-3.8449-1.18-5.4415-2.6706-1.7595-1.6769-3.7472-3.5401-7.5921-3.5401h-0.42359c-0.55392-0.93162-1.6292-1.5527-2.8348-1.5527-1.7921 0-3.2584 1.3974-3.2584 3.1053 0 1.708 1.4663 3.1054 3.2584 3.1054 1.2056 0 2.2483-0.62106 2.8348-1.5527h0.42359c2.509 0 3.7472 1.18 5.3112 2.6396 0.71685 0.68316 1.4989 1.3974 2.4764 2.0495-0.87977 0.59001-1.6292 1.3042-2.3461 1.9564-1.5966 1.4906-2.8674 2.6706-5.4415 2.6706h-0.42359c-0.55392-0.93162-1.6292-1.5527-2.8348-1.5527-1.7921 0-3.2584 1.3974-3.2584 3.1054 0 1.7079 1.4663 3.1054 3.2584 3.1054 1.2056 0 2.2483-0.62107 2.8348-1.5527h0.42359c3.9101 0 6.028-1.9874 7.7224-3.5712 1.564-1.4595 2.8022-2.6395 5.3112-2.6395h0.58651v1.7079zm-22.809-4.3475c-1.0753 0-1.955-0.83843-1.955-1.8632 0-1.0248 0.87977-1.8632 1.955-1.8632 1.0753 0 1.955 0.83843 1.955 1.8632 0 1.0248-0.87976 1.8632-1.955 1.8632zm0 12.421c-1.0753 0-1.955-0.83845-1.955-1.8632 0-1.0248 0.87977-1.8632 1.955-1.8632 1.0753 0 1.955 0.83845 1.955 1.8632 0 1.0248-0.87976 1.8632-1.955 1.8632z" fill="#191d1f" stroke-width=".3181"/>
        <circle cx="38.442" cy="386.13" r="19.21" fill="none" stroke="#155c8f" stroke-width="1.0978"/>
        <circle cx="38.442" cy="386.13" r="17.012" fill="none" stroke="#155c8f" stroke-width=".9722"/>
        </g>
        </g>
      </svg>
    </div>

  </footer>
  {% block scripts %}{% endblock %}
  </body>
</html>